services:
  ex1:
    build:
      context: ./ex1
    ports:
      - "17000:17000"
    depends_on:
      - mongodb
  
  ex2:
    build:
      context: ./ex2
    ports:
      - "17001:17001"
    depends_on:
      - ex1
  
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    depends_on:
      - seed
  
  seed:
    image: mongo
    volumes:
      - ./data/livros.json:/livros.json
    command: mongoimport --host mongodb -d livros -c livros --type json --file livros.json --jsonArray